# Generated by Django 4.1 on 2022-08-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.CharField(max_length=255, verbose_name='API URL')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Order number')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.status', verbose_name='Status')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Warehouse')),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO store_status ('title') VALUES ('In progress');",
        ),
        migrations.RunSQL(
            "INSERT INTO store_status ('title') VALUES ('Stored');",
        ),
        migrations.RunSQL(
            "INSERT INTO store_status ('title') VALUES ('Sent');",
        ),
    ]
